// src/tipoRules.js
// Reglas predictivas de Tipo de gasto.
// Generadas a partir del histórico real de SMTo (Saldos 2026): 18,846 transacciones
// que cruzan 23 hojas (BBVA, Banamex, Monex, Clara, Kapital, etc.) entre 2024 y 2025.
//
// Cada regla mapea un patrón observable en el nombre del PROVEEDOR (emisor del CFDI)
// o en la descripción del producto/servicio del CFDI, hacia su Tipo de gasto base.
// La lógica de sufijo "Ventas" se aplica en autoDetectTipo() según la categoría
// del colaborador (Ventas/Socio → sufijo "Ventas", el resto → tipo base).
//
// Orden: patrones más largos primero para que ganen en el match (greedy specificity).

export const TIPO_RULES = [
  ['AMAZON MX MARKETPLACE', 'Marketing'],
  ['REST DENNYS CHIHUAHUA', 'Consumo'],
  ['SORIANA981TLAQUEPAQUE', 'Consumo'],
  ['MERCADOPAGO AEROCHAR', 'Envíos'],
  ['STARBUCKS SAN MARCOS', 'Consumo'],
  ['BURGER KING SENDERO', 'Consumo'],
  ['OXXO GASCORDILLERAS', 'Gasolina'],
  ['OXXO GASTEQUEPEXPAN', 'Gasolina'],
  ['STARBUCKS SAN PEDRO', 'Gastos Rep (Representación)'],
  ['COSTCO GUADALAJARA', 'Consumo'],
  ['FIESTA INN NOGALES', 'Consumo'],
  ['AEROMEXICO CARGO', 'Envíos'],
  ['HOLIDAYINNCIUDAD', 'Hotel'],
  ['OXXO GASCRUCERO', 'Gasolina'],
  ['REST LA COSECHA', 'Consumo'],
  ['STARBUCKS CITAD', 'Gastos Rep (Representación)'],
  ['AEROMEXICO WEB', 'Avión'],
  ['CARLS JR STIVA', 'Consumo'],
  ['ESTACIONAMIENT', 'Estacionamiento'],
  ['GASNECTARMARIA', 'Gasolina'],
  ['STARBUCKS CARR', 'Gastos Rep (Representación)'],
  ['TACOS REYNALDO', 'Gastos Rep (Representación)'],
  ['CLIP MX ESTAC', 'Estacionamiento'],
  ['HOTEL HAMTPON', 'Hotel'],
  ['HOTEL MEDRANO', 'Hotel'],
  ['OXXO TERMINAL', 'Consumo'],
  ['PAGANDO ESTAC', 'Estacionamiento'],
  ['REFACCIONARIA', 'Manto Auto (Mantenimiento)'],
  ['REST FORJADOR', 'Consumo'],
  ['STARBUCKS EST', 'Gastos Rep (Representación)'],
  ['STARBUCKS GDL', 'Gastos Rep (Representación)'],
  ['STARBUCKS LAS', 'Gastos Rep (Representación)'],
  ['WYNDHAMGARDEN', 'Hotel'],
  ['BEST WESTERN', 'Hotel'],
  ['CHILIS STIVA', 'Consumo'],
  ['CITY EXPRESS', 'Hotel'],
  ['COMBUSTIBLES', 'Gasolina'],
  ['GRUPO FLECHA', 'Envíos'],
  ['HOTEL ENCORE', 'Hotel'],
  ['HOTEL QUARTZ', 'Hotel'],
  ['LA SABROSITA', 'Consumo'],
  ['OFFICE DEPOT', 'Papelería'],
  ['REST CASCADA', 'Consumo'],
  ['A1088BMXN02', 'IT & SW (Software/Sistemas)'],
  ['ANTIESTATIC', 'Uniformes'],
  ['ELEVEN PQUE', 'Consumo'],
  ['RCH CUCAPAH', 'Gasolina'],
  ['RECAUDADORA', 'Manto Auto (Mantenimiento)'],
  ['REST CHILIS', 'Consumo'],
  ['SUPERCENTER', 'Consumo'],
  ['VIVAAEROBUS', 'Avión'],
  ['AEROPUERTO', 'Estacionamiento'],
  ['AUTOTRANSP', 'Taxi'],
  ['FIESTA INN', 'Hotel'],
  ['GASOLINERA', 'Gasolina'],
  ['HOME DEPOT', 'Herramientas'],
  ['MIT TRANSP', 'Avión'],
  ['OFFICE MAX', 'Papelería'],
  ['ONE MINUTE', 'Estacionamiento'],
  ['SUPER SERV', 'Gasolina'],
  ['TOTAL PLAY', 'IT & SW (Software/Sistemas)'],
  ['VOLARISMXN', 'Avión'],
  ['AERONAVES', 'Avión'],
  ['ANTHROPIC', 'IT & SW (Software/Sistemas)'],
  ['APPLE COM', 'IT & SW (Software/Sistemas)'],
  ['BODECATTA', 'Consumo'],
  ['CHIHUAHUA', 'Herramientas'],
  ['EBSSATAXI', 'Taxi'],
  ['FIESTAINN', 'Consumo'],
  ['INSTAGRAM', 'Marketing'],
  ['MCDONALDS', 'Consumo'],
  ['MEGACABLE', 'IT & SW (Software/Sistemas)'],
  ['MICROSOFT', 'IT & SW (Software/Sistemas)'],
  ['OFFICEMAX', 'Papelería'],
  ['SAMS CLUB', 'Consumo'],
  ['STARBUCKS', 'Consumo'],
  ['TACOS SAN', 'Gastos Rep (Representación)'],
  ['TOTALPLAY', 'IT & SW (Software/Sistemas)'],
  ['TST BEACH', 'Consumo'],
  ['UBER EATS', 'Consumo'],
  ['AUTOZONE', 'Manto Auto (Mantenimiento)'],
  ['CAMPOMAR', 'Gastos Rep (Representación)'],
  ['CHEDRAUI', 'Consumo'],
  ['ESTACION', 'Gasolina'],
  ['ESTAFETA', 'Envíos'],
  ['FACEBOOK', 'Marketing'],
  ['INTERJET', 'Avión'],
  ['LA COMER', 'Consumo'],
  ['LINKEDIN', 'Marketing'],
  ['MARRIOTT', 'Hotel'],
  ['MOVISTAR', 'Celular'],
  ['ONE PARK', 'Estacionamiento'],
  ['SANBORNS', 'Consumo'],
  ['SERV LAS', 'Gasolina'],
  ['AEROMAR', 'Avión'],
  ['BOOKING', 'Hotel'],
  ['CASETAS', 'Casetas'],
  ['CHEVRON', 'Gasolina'],
  ['DROPBOX', 'IT & SW (Software/Sistemas)'],
  ['HOLAFLY', 'Celular'],
  ['HOLIDAY', 'Hotel'],
  ['NETFLIX', 'IT & SW (Software/Sistemas)'],
  ['NEUFELD', 'Consumo'],
  ['OXXO EL', 'Gastos Rep (Representación)'],
  ['PARKING', 'Estacionamiento'],
  ['RECARGA', 'Casetas'],
  ['REDPACK', 'Envíos'],
  ['SORIANA', 'Consumo'],
  ['SPOTIFY', 'IT & SW (Software/Sistemas)'],
  ['TORTAAS', 'Gastos Rep (Representación)'],
  ['VOLARIS', 'Avión'],
  ['WALMART', 'Consumo'],
  ['AIRBNB', 'Hotel'],
  ['AMERIX', 'Consumo'],
  ['BP GAS', 'Gasolina'],
  ['BUDGET', 'Renta Auto'],
  ['CABIFY', 'Taxi'],
  ['CF SAN', 'Consumo'],
  ['CHILIS', 'Consumo'],
  ['DENNYS', 'Gastos Rep (Representación)'],
  ['DQ LAS', 'Consumo'],
  ['GITHUB', 'IT & SW (Software/Sistemas)'],
  ['GOOGLE', 'IT & SW (Software/Sistemas)'],
  ['GSUITE', 'IT & SW (Software/Sistemas)'],
  ['HILTON', 'Hotel'],
  ['IBERIA', 'Avión'],
  ['MARISA', 'Consumo'],
  ['NOTION', 'IT & SW (Software/Sistemas)'],
  ['OPENAI', 'IT & SW (Software/Sistemas)'],
  ['PETRO7', 'Gasolina'],
  ['REFACC', 'Manto Auto (Mantenimiento)'],
  ['REPSOL', 'Gasolina'],
  ['RINCON', 'Gasolina'],
  ['STEREN', 'Herramientas'],
  ['SUBWAY', 'Consumo'],
  ['TELCEL', 'Celular'],
  ['TELMEX', 'IT & SW (Software/Sistemas)'],
  ['TIKTOK', 'Marketing'],
  ['TRUPER', 'Herramientas'],
  ['ABARR', 'Consumo'],
  ['ADOBE', 'IT & SW (Software/Sistemas)'],
  ['ADOLF', 'Gasolina'],
  ['CHILI', 'Consumo'],
  ['FEDEX', 'Envíos'],
  ['FERRE', 'Herramientas'],
  ['FOGON', 'Consumo'],
  ['GASOL', 'Gasolina'],
  ['HERTZ', 'Renta Auto'],
  ['HYATT', 'Hotel'],
  ['MAZDA', 'Manto Auto (Mantenimiento)'],
  ['MOBIL', 'Gasolina'],
  ['PARCO', 'Estacionamiento'],
  ['PEMEX', 'Gasolina'],
  ['PETRO', 'Gasolina'],
  ['PIZZA', 'Consumo'],
  ['PUERT', 'Estacionamiento'],
  ['SHELL', 'Gasolina'],
  ['SLACK', 'IT & SW (Software/Sistemas)'],
  ['SUSHI', 'Consumo'],
  ['TACOS', 'Consumo'],
  ['TAXIS', 'Taxi'],
  ['AT T', 'Celular'],
  ['ATTA', 'Taxi'],
  ['AVIS', 'Renta Auto'],
  ['BRIX', 'Consumo'],
  ['DIDI', 'Taxi'],
  ['GRAB', 'Taxi'],
  ['GULF', 'Gasolina'],
  ['HOME', 'Herramientas'],
  ['IZZI', 'IT & SW (Software/Sistemas)'],
  ['JMAS', 'Renta Oficina'],
  ['LYFT', 'Taxi'],
  ['META', 'Marketing'],
  ['MSFT', 'IT & SW (Software/Sistemas)'],
  ['PAYU', 'IT & SW (Software/Sistemas)'],
  ['SIXT', 'Renta Auto'],
  ['TAXI', 'Taxi'],
  ['TOKS', 'Consumo'],
  ['UBER', 'Taxi'],
  ['VIPS', 'Consumo'],
  ['VIVA', 'Avión'],
  ['ZOOM', 'IT & SW (Software/Sistemas)'],
  ['AMK', 'Gastos Rep (Representación)'],
  ['AWS', 'IT & SW (Software/Sistemas)'],
  ['CFE', 'Renta Oficina'],
  ['DHL', 'Envíos'],
  ['GAS', 'Gasolina'],
  ['GOB', 'Manto Auto (Mantenimiento)'],
  ['KIA', 'Manto Auto (Mantenimiento)'],
  ['PZA', 'Casetas'],
  ['REA', 'Casetas'],
  ['UPS', 'Envíos'],
]

// Tipos base que tienen variante "Ventas" para colaboradores de Ventas/Socio.
// Los que NO están en este map mantienen su tipo base aunque la categoría sea Ventas.
const VENTAS_VARIANT = {
  'Avión': 'Avión Ventas',
  'Casetas': 'Casetas Ventas',
  'Estacionamiento': 'Estacionamiento Ventas',
  'Gasolina': 'Gasolina Ventas',
  'Herramientas': 'Herramientas Ventas',
  'Hotel': 'Hotel Ventas',
  'Consumo': 'Gastos Rep (Representación)',
  'Taxi': 'Gastos Rep (Representación)',
}

/**
 * Auto-detecta el Tipo de gasto a partir del proveedor + descripción del CFDI.
 * @param {string} proveedor    Nombre del emisor del CFDI (ej. "OXXO GAS S.A. DE C.V.")
 * @param {string} descripcion  Primera línea de la descripción del concepto del CFDI
 * @param {string} categoria    Categoría del colaborador: 'Admin'|'Servicio'|'Ventas'|'Socio'
 * @returns {string} Tipo de gasto (ej. "Gasolina" o "Gasolina Ventas")
 */
export function autoDetectTipo(proveedor, descripcion, categoria) {
  const texto = `${proveedor || ''} ${descripcion || ''}`.toUpperCase()
  const isVentas = categoria === 'Ventas' || categoria === 'Socio'

  for (const [kw, tipoBase] of TIPO_RULES) {
    if (texto.includes(kw)) {
      return isVentas && VENTAS_VARIANT[tipoBase] ? VENTAS_VARIANT[tipoBase] : tipoBase
    }
  }

  // Sin match → fallback genérico (mismo comportamiento que la versión anterior)
  return isVentas ? 'Gastos Rep (Representación)' : 'Consumo'
}
