// src/tipoRules.js
// Reglas predictivas de Tipo de gasto — v5
// 18,846 transacciones históricas SMTo + razones sociales fiscales mexicanas + conceptos CFDI
// Keywords largos primero (greedy specificity). Sin keywords ≤3 chars ambiguos.

export const TIPO_RULES = [
  // ── Proveedores SMTO con asignación fija (lista 2026-05) ────────────────
  // Estas reglas viven ARRIBA de las genéricas para ganar prioridad. P.ej.
  // FEDEX abajo dice "Envíos" pero aquí lo forzamos a "Aduana" por convenio
  // interno SMTO.
  ['BISMAK',         'Consultoría'],
  ['C Y C ',         'Consultoría'],
  ['C Y C,',         'Consultoría'],
  ['JUAN M ROB',     'Consultoría'],
  ['JUAN MANUEL ROB','Consultoría'],
  ['ZUÑIGA',         'Contador'],
  ['ZUNIGA',         'Contador'],
  ['ZÚÑIGA',         'Contador'],
  // El SAT registró el Ñ del despacho como '&' literal: 'ZU&IGA RODRIGUEZ Y CIA'.
  // Agregamos la variante exacta para que la auto-detección funcione tal cual
  // viene en el CFDI sin tocar el XML.
  ['ZU&IGA',         'Contador'],
  ['DHL ',           'Envíos'],
  ['DHL,',           'Envíos'],
  ['DHL EXPRESS',    'Envíos'],
  ['DHL DE MEXICO',  'Envíos'],
  ['DHL MEXICO',     'Envíos'],
  ['FEDEX',          'Aduana'],          // override del FEDEX→Envíos genérico
  ['INTEGRADORA',    'Aduana'],
  ['DESP CANO',      'Aduana'],
  ['DESPACHO CANO',  'Aduana'],
  ['IBG ',           'Comercio Exterior'],
  ['KLF ',           'Comercio Exterior'],
  ['MBGE',           'IT & SW (Software/Sistemas)'],
  ['SFERP',          'IT & SW (Software/Sistemas)'],
  ['TOTALPLAY',      'IT & SW (Software/Sistemas)'],
  ['TOTAL PLAY',     'IT & SW (Software/Sistemas)'],
  ['PROVISOR',       'COGS'],
  ['TEKTRONIX',      'COGS'],
  ['ROHDE',          'COGS'],
  ['GASNGO',         'Gasolina'],
  ['ILIANA ALV',     'Renta Oficina'],
  ['ILIANA ALVAREZ', 'Renta Oficina'],
  ['LA VENTOLERA',   'Renta Oficina'],
  ['TOMAS VALLES',   'Renta Oficina'],
  ['ITESO',          'Renta Oficina'],
  ['FIAT ',          'Renta Oficina'],   // override de FIAT (marca de auto)
  ['VANRENTA',       'Automóvil'],
  // ── Fin proveedores SMTO ────────────────────────────────────────────────

  // ── Equipo de cómputo / PC ──────────────────────────────────────────────
  ['EQUIPO DE COMPUTO',    'PC (Equipo)'],
  ['EQUIPO DE CÓMPUTO',   'PC (Equipo)'],
  ['EQUIPO DE ESCRITORIO','PC (Equipo)'],
  ['COMPUTADORA PORTATIL','PC (Equipo)'],
  ['COMPUTADORA PORTÁTIL','PC (Equipo)'],
  ['COMPUTADORA PERSONAL', 'PC (Equipo)'],
  ['COMPUTADORA',          'PC (Equipo)'],
  ['ALIENWARE',            'PC (Equipo)'],
  ['THINKPAD',             'PC (Equipo)'],
  ['NOTEBOOK',             'PC (Equipo)'],
  ['SERVIDOR',             'PC (Equipo)'],
  ['IMPRESORA',            'PC (Equipo)'],
  ['MACBOOK',              'PC (Equipo)'],
  ['LAPTOP',               'PC (Equipo)'],
  ['TABLET',               'PC (Equipo)'],
  // ── Fin equipo de cómputo ───────────────────────────────────────────────
  ['COMERCIALIZADORA DE COMBUSTIBLES', 'Gasolina'],
  ['COMISION FEDERAL DE ELECTRICIDAD', 'Renta Oficina'],
  ['OPERADORA DE ESTACIONAMIENTOS', 'Estacionamiento'],
  ['CONCESIONARIA DE AUTOPISTA', 'Casetas'],
  ['MATERIALES DE CONSTRUCCION', 'Herramientas'],
  ['TARIFA SERVICIO TRANSPORTE', 'Taxi'],
  ['ARRENDADORA DE VEHICULOS', 'Renta Auto'],
  ['OPERADORA DE FRANQUICIAS', 'Consumo'],
  ['TRANSPORTADORA EJECUTIVA', 'Taxi'],
  ['ADMINISTRADORA HOTELERA', 'Hotel'],
  ['FACTURACION ELECTRONICA', 'IT & SW (Software/Sistemas)'],
  ['MENSAJERIA Y PAQUETERIA', 'Envíos'],
  ['REFACCIONES Y SERVICIOS', 'Manto Auto (Mantenimiento)'],
  ['SERVICIO DE COMBUSTIBLE', 'Gasolina'],
  ['SERVICIOS DE TRANSPORTE', 'Taxi'],
  ['AEROENLACES NACIONALES', 'Avión'],
  ['INVERSIONISTA HOTELERO', 'Hotel'],
  ['SERVICIO DE MENSAJERIA', 'Envíos'],
  ['SERVICIO DE TRANSPORTE', 'Taxi'],
  ['SERVICIOS DE ALIMENTOS', 'Consumo'],
  ['SISTEMA INTERMUNICIPAL', 'Renta Oficina'],
  ['TRANSPORTES TURISTICOS', 'Taxi'],
  ['AMAZON MX MARKETPLACE', 'Marketing'],
  ['REST DENNYS CHIHUAHUA', 'Consumo Viáticos'],
  ['SORIANA981TLAQUEPAQUE', 'Consumo'],
  ['COMPANIA DE AVIACION', 'Avión'],
  ['COMPAÑIA DE AVIACION', 'Avión'],
  ['ESTACION DE SERVICIO', 'Gasolina'],
  ['MERCADOPAGO AEROCHAR', 'Envíos'],
  ['OPERADORA DE HOTELES', 'Hotel'],
  ['SERVICIOS LOGISTICOS', 'Envíos'],
  ['STARBUCKS SAN MARCOS', 'Consumo'],
  ['TRANSPORTE EJECUTIVO', 'Taxi'],
  ['ALIMENTOS Y BEBIDAS', 'Consumo'],
  ['AT&T COMUNICACIONES', 'Celular'],
  ['BURGER KING SENDERO', 'Consumo'],
  ['CONCESIONARIA VUELA', 'Avión'],
  ['HABITACION SENCILLA', 'Hotel'],
  ['LLANTAS Y SERVICIOS', 'Manto Auto (Mantenimiento)'],
  ['OXXO GASCORDILLERAS', 'Gasolina'],
  ['OXXO GASTEQUEPEXPAN', 'Gasolina'],
  ['SERVICIO AUTOMOTRIZ', 'Manto Auto (Mantenimiento)'],
  ['STARBUCKS SAN PEDRO', 'Gastos Rep (Representación)'],
  ['SUSCRIPCION MENSUAL', 'IT & SW (Software/Sistemas)'],
  ['TRASLADO AEROPUERTO', 'Taxi'],
  ['AEROVIAS DE MEXICO', 'Avión'],
  ['COSTCO GUADALAJARA', 'Consumo'],
  ['FIESTA INN NOGALES', 'Consumo'],
  ['NOCHE DE HOSPEDAJE', 'Hotel'],
  ['OPERADORA HOTELERA', 'Hotel'],
  ['PROMOTORA HOTELERA', 'Hotel'],
  ['RENTA DE CAMIONETA', 'Renta Auto'],
  ['TRANSPORTE PRIVADO', 'Taxi'],
  ['TRANSPORTES AEREOS', 'Avión'],
  ['POSADAS DE MEXICO', 'Hotel'],
  ['RENTA DE VEHICULO', 'Renta Auto'],
  ['SOLUCION FACTIBLE', 'IT & SW (Software/Sistemas)'],
  ['SUSCRIPCION ANUAL', 'IT & SW (Software/Sistemas)'],
  ['AEROMEXICO CARGO', 'Envíos'],
  ['AEROVIAS EMPRESA', 'Avión'],
  ['ESTACIONAMIENTOS', 'Estacionamiento'],
  ['HABITACION DOBLE', 'Hotel'],
  ['HOLIDAYINNCIUDAD', 'Hotel'],
  ['RADIOMOVIL DIPSA', 'Celular'],
  ['SERVICIO DE AGUA', 'Renta Oficina'],
  ['TARIFA POR VIAJE', 'Taxi'],
  ['BOLETO DE AVION', 'Avión'],
  ['CADENA HOTELERA', 'Hotel'],
  ['GRUPO ALIMENTOS', 'Consumo'],
  ['LICENCIA DE USO', 'IT & SW (Software/Sistemas)'],
  ['OXXO GASCRUCERO', 'Gasolina'],
  ['REST LA COSECHA', 'Consumo Viáticos'],
  ['STARBUCKS CITAD', 'Gastos Rep (Representación)'],
  ['TALLER MECANICO', 'Manto Auto (Mantenimiento)'],
  ['TARIFA DE VIAJE', 'Taxi'],
  ['ABC AEROLINEAS', 'Avión'],
  ['AEROMEXICO WEB', 'Avión'],
  ['CARLS JR STIVA', 'Consumo'],
  ['ESTACIONAMIENT', 'Estacionamiento'],
  ['GASNECTARMARIA', 'Gasolina'],
  ['STARBUCKS CARR', 'Gastos Rep (Representación)'],
  ['TACOS REYNALDO', 'Gastos Rep (Representación)'],
  ['TAR AEROLINEAS', 'Avión'],
  ['VUELA COMPANIA', 'Avión'],
  ['VUELA COMPAÑIA', 'Avión'],
  ['CLIP MX ESTAC', 'Estacionamiento'],
  ['GRUPO POSADAS', 'Hotel'],
  ['HOTEL HAMTPON', 'Hotel'],
  ['HOTEL MEDRANO', 'Hotel'],
  ['MAGNICHARTERS', 'Avión'],
  ['OXXO TERMINAL', 'Consumo'],
  ['PAGANDO ESTAC', 'Estacionamiento'],
  ['REFACCIONARIA', 'Manto Auto (Mantenimiento)'],
  ['RENTA DE AUTO', 'Renta Auto'],
  ['REST FORJADOR', 'Consumo Viáticos'],
  ['STARBUCKS EST', 'Gastos Rep (Representación)'],
  ['STARBUCKS GDL', 'Gastos Rep (Representación)'],
  ['STARBUCKS LAS', 'Gastos Rep (Representación)'],
  ['WYNDHAMGARDEN', 'Hotel'],
  ['AGUA POTABLE', 'Renta Oficina'],
  ['BEST WESTERN', 'Hotel'],
  ['BOLETO AEREO', 'Avión'],
  ['CHILIS STIVA', 'Consumo'],
  ['CITY EXPRESS', 'Hotel'],
  ['COMBUSTIBLES', 'Gasolina'],
  ['CONFECCIONES', 'Uniformes'],
  ['GRUPO FLECHA', 'Envíos'],
  ['HOTEL ENCORE', 'Hotel'],
  ['HOTEL QUARTZ', 'Hotel'],
  ['LA SABROSITA', 'Consumo'],
  ['OFFICE DEPOT', 'Papelería'],
  ['OPERADORA OM', 'Hotel'],
  ['PANIFICADORA', 'Consumo'],
  ['PLAN MENSUAL', 'IT & SW (Software/Sistemas)'],
  ['RENTA CHIREY', 'Renta Auto'],
  ['RENTA NISSAN', 'Renta Auto'],
  ['RENTA TOYOTA', 'Renta Auto'],
  ['REST CASCADA', 'Consumo'],
  ['RESTAURANTES', 'Consumo Viáticos'],
  ['TARIFA AEREA', 'Avión'],
  ['A1088BMXN02', 'IT & SW (Software/Sistemas)'],
  ['AEROENLACES', 'Avión'],
  ['AEROLITORAL', 'Avión'],
  ['ANTIESTATIC', 'Uniformes'],
  ['DOMINIO WEB', 'IT & SW (Software/Sistemas)'],
  ['ELEVEN PQUE', 'Consumo'],
  ['GAS NATURAL', 'Renta Oficina'],
  ['GASOLINERIA', 'Gasolina'],
  ['HABITACION ', 'Hotel'],
  ['HOSPITALITY', 'Hotel'],
  ['OFFICEDEPOT', 'Papelería'],
  ['RCH CUCAPAH', 'Gasolina'],
  ['RECAUDADORA', 'Manto Auto (Mantenimiento)'],
  ['REST CHILIS', 'Consumo'],
  ['SUPERCENTER', 'Consumo'],
  ['VIVAAEROBUS', 'Avión'],
  ['AEROLINEAS', 'Avión'],
  ['AEROPUERTO', 'Estacionamiento'],
  ['AUTOMOTRIZ', 'Manto Auto (Mantenimiento)'],
  ['AUTOPISTAS', 'Casetas'],
  ['AUTOTRANSP', 'Taxi'],
  ['CAR RENTAL', 'Renta Auto'],
  ['FERRETERIA', 'Herramientas'],
  ['FIESTA INN', 'Hotel'],
  ['GASOLINERA', 'Gasolina'],
  ['HOME DEPOT', 'Herramientas'],
  ['MIT TRANSP', 'Avión'],
  ['OFFICE MAX', 'Papelería'],
  ['ONE MINUTE', 'Estacionamiento'],
  ['PAQUETERIA', 'Envíos'],
  ['PEGASO PCS', 'Celular'],
  ['RENT A CAR', 'Renta Auto'],
  ['RENTA AUTO', 'Renta Auto'],
  ['ROOM NIGHT', 'Hotel'],
  ['SUPER SERV', 'Gasolina'],
  ['TLAPALERIA', 'Herramientas'],
  ['TOTAL PLAY', 'IT & SW (Software/Sistemas)'],
  ['TRANS GUTS', 'Taxi'],
  ['VOLARISMXN', 'Avión'],
  ['AEROLINEA', 'Avión'],
  ['AERONAVES', 'Avión'],
  ['ANTHROPIC', 'IT & SW (Software/Sistemas)'],
  ['APPLE COM', 'IT & SW (Software/Sistemas)'],
  ['BODECATTA', 'Consumo'],
  ['CAFETERIA', 'Consumo'],
  ['CHIHUAHUA', 'Herramientas'],
  ['EBSSATAXI', 'Taxi'],
  ['FACTURAMA', 'IT & SW (Software/Sistemas)'],
  ['FACTURIFY', 'IT & SW (Software/Sistemas)'],
  ['FIESTAINN', 'Consumo'],
  ['HOSPEDAJE', 'Hotel'],
  ['INSTAGRAM', 'Marketing'],
  ['MCDONALDS', 'Consumo'],
  ['MEGACABLE', 'IT & SW (Software/Sistemas)'],
  ['MICROSOFT', 'IT & SW (Software/Sistemas)'],
  ['OFFICEMAX', 'Papelería'],
  ['PAPELERIA', 'Papelería'],
  ['SAMS CLUB', 'Consumo'],
  ['STARBUCKS', 'Consumo'],
  ['TACOS SAN', 'Gastos Rep (Representación)'],
  ['TOTALPLAY', 'IT & SW (Software/Sistemas)'],
  ['TST BEACH', 'Consumo'],
  ['UBER EATS', 'Consumo'],
  ['UNIFORMES', 'Uniformes'],
  ['AUTOZONE', 'Manto Auto (Mantenimiento)'],
  ['AVIACION', 'Avión'],
  ['CAMPOMAR', 'Gastos Rep (Representación)'],
  ['CHEDRAUI', 'Consumo'],
  ['ESTACION', 'Gasolina'],
  ['ESTAFETA', 'Envíos'],
  ['FACEBOOK', 'Marketing'],
  ['HOTELERA', 'Hotel'],
  ['IMPRENTA', 'Papelería'],
  ['INTERJET', 'Avión'],
  ['IUSACELL', 'Celular'],
  ['LA COMER', 'Consumo'],
  ['LINKEDIN', 'Marketing'],
  ['MARRIOTT', 'Hotel'],
  ['MOVISTAR', 'Celular'],
  ['ONE PARK', 'Estacionamiento'],
  ['SANBORNS', 'Consumo'],
  ['SERV LAS', 'Gasolina'],
  ['SOFTWARE', 'IT & SW (Software/Sistemas)'],
  ['TEXTILES', 'Uniformes'],
  ['AEROMAR', 'Avión'],
  ['BOOKING', 'Hotel'],
  ['CASETAS', 'Casetas'],
  ['CHEVRON', 'Gasolina'],
  ['CONTPAQ', 'IT & SW (Software/Sistemas)'],
  ['DROPBOX', 'IT & SW (Software/Sistemas)'],
  ['HOLAFLY', 'Celular'],
  ['HOLIDAY', 'Hotel'],
  ['HOSTING', 'IT & SW (Software/Sistemas)'],
  ['NETFLIX', 'IT & SW (Software/Sistemas)'],
  ['NEUFELD', 'Consumo'],
  ['OXXO EL', 'Gastos Rep (Representación)'],
  ['PARKING', 'Estacionamiento'],
  ['RECARGA', 'Casetas'],
  ['REDPACK', 'Envíos'],
  ['RENTING', 'Renta Auto'],
  ['SORIANA', 'Consumo'],
  ['SPOTIFY', 'IT & SW (Software/Sistemas)'],
  ['TORTAAS', 'Gastos Rep (Representación)'],
  ['VOLARIS', 'Avión'],
  ['WALMART', 'Consumo'],
  ['AIRBNB', 'Hotel'],
  ['AMERIX', 'Consumo'],
  ['BP GAS', 'Gasolina'],
  ['BUDGET', 'Renta Auto'],
  ['CABIFY', 'Taxi'],
  ['CAPUFE', 'Casetas'],
  ['CF SAN', 'Consumo'],
  ['CHILIS', 'Consumo'],
  ['DENNYS', 'Gastos Rep (Representación)'],
  ['DQ LAS', 'Consumo'],
  ['GITHUB', 'IT & SW (Software/Sistemas)'],
  ['GOOGLE', 'IT & SW (Software/Sistemas)'],
  ['GSUITE', 'IT & SW (Software/Sistemas)'],
  ['HILTON', 'Hotel'],
  ['IBERIA', 'Avión'],
  ['MARISA', 'Consumo'],
  ['NOTION', 'IT & SW (Software/Sistemas)'],
  ['OPENAI', 'IT & SW (Software/Sistemas)'],
  ['PETRO7', 'Gasolina'],
  ['REFACC', 'Manto Auto (Mantenimiento)'],
  ['REPSOL', 'Gasolina'],
  ['RINCON', 'Gasolina'],
  ['STEREN', 'Herramientas'],
  ['SUBWAY', 'Consumo'],
  ['TELCEL', 'Celular'],
  ['TELMEX', 'IT & SW (Software/Sistemas)'],
  ['TIKTOK', 'Marketing'],
  ['TRUPER', 'Herramientas'],
  ['UNEFON', 'Celular'],
  ['VUELO ', 'Avión'],
  ['ABARR', 'Consumo'],
  ['ADOBE', 'IT & SW (Software/Sistemas)'],
  ['ADOLF', 'Gasolina'],
  ['CHILI', 'Consumo'],
  ['CLOUD', 'IT & SW (Software/Sistemas)'],
  ['FEDEX', 'Envíos'],
  ['FERRE', 'Herramientas'],
  ['FOGON', 'Consumo'],
  ['GASOL', 'Gasolina'],
  ['HERTZ', 'Renta Auto'],
  ['HYATT', 'Hotel'],
  ['MAZDA', 'Manto Auto (Mantenimiento)'],
  ['MOBIL', 'Gasolina'],
  ['PARCO', 'Estacionamiento'],
  ['PEAJE', 'Casetas'],
  ['PEMEX', 'Gasolina'],
  ['PETRO', 'Gasolina'],
  ['PIZZA', 'Consumo'],
  ['PUERT', 'Estacionamiento'],
  ['SHELL', 'Gasolina'],
  ['SLACK', 'IT & SW (Software/Sistemas)'],
  ['SUSHI', 'Consumo'],
  ['TACOS', 'Consumo'],
  ['TAXIS', 'Taxi'],
  ['AT T', 'Celular'],
  ['ATTA', 'Taxi'],
  ['AVIS', 'Renta Auto'],
  ['BRIX', 'Consumo'],
  ['DIDI', 'Taxi'],
  ['GRAB', 'Taxi'],
  ['GULF', 'Gasolina'],
  ['IZZI', 'IT & SW (Software/Sistemas)'],
  ['JMAS', 'Renta Oficina'],
  ['LYFT', 'Taxi'],
  ['META', 'Marketing'],
  ['MSFT', 'IT & SW (Software/Sistemas)'],
  ['PAYU', 'IT & SW (Software/Sistemas)'],
  ['SIXT', 'Renta Auto'],
  ['TAXI', 'Taxi'],
  ['TOKS', 'Consumo'],
  ['UBER', 'Taxi'],
  ['VIPS', 'Consumo'],
  ['VIVA', 'Avión'],
  ['ZOOM', 'IT & SW (Software/Sistemas)'],
  ['AWS', 'IT & SW (Software/Sistemas)'],
  ['CFE', 'Renta Oficina'],
  ['DHL', 'Envíos'],
  ['GAS', 'Gasolina'],
  ['PZA', 'Casetas'],
  ['UPS', 'Envíos'],
]

const VENTAS_VARIANT = {
  'Avión': 'Avión Ventas',
  'Casetas': 'Casetas Ventas',
  'Estacionamiento': 'Estacionamiento Ventas',
  'Gasolina': 'Gasolina Ventas',
  'Herramientas': 'Herramientas Ventas',
  'Hotel': 'Hotel Ventas',
  'Consumo': 'Gastos Rep (Representación)',
  'Consumo Viáticos': 'Gastos Rep Viáticos',
  'Taxi': 'Gastos Rep (Representación)',
}

// Prefijos de ClaveProdServ SAT que corresponden a equipo de cómputo / IT.
// 4321xxxx = Hardware de cómputo, 4322xxxx = Periféricos, 4323xxxx = Redes.
const SAT_PC_PREFIXES = ['4321', '4322', '4323']

/**
 * @param {string} proveedor      Nombre del emisor del CFDI
 * @param {string} descripcion    Primera línea del concepto del CFDI
 * @param {string} categoria      'Admin'|'Servicio'|'Ventas'|'Socio'
 * @param {string} claveProdServ  Código SAT del producto (opcional)
 */
export function autoDetectTipo(proveedor, descripcion, categoria, claveProdServ = '') {
  const texto = `${proveedor || ''} ${descripcion || ''}`.toUpperCase()
  const isVentas = categoria === 'Ventas' || categoria === 'Socio'

  // FACTURIFY es plataforma de facturación usada por choferes/taxistas.
  // Cuando el concepto es "TARIFA" es la tarifa del viaje, no suscripción de software.
  if ((proveedor || '').toUpperCase().includes('FACTURIFY') &&
      (descripcion || '').toUpperCase().trim() === 'TARIFA') {
    return isVentas ? 'Gastos Rep (Representación)' : 'Taxi'
  }

  // REFIEL → si la descripción empieza con "RENTA" es Automóvil; en cualquier
  // otro caso cae a las reglas genéricas / fallback.
  if ((proveedor || '').toUpperCase().includes('REFIEL') &&
      (descripcion || '').toUpperCase().trim().startsWith('RENTA')) {
    return 'Automóvil'
  }

  // 1. Primero: buscar en reglas conocidas (marcas, razones sociales, conceptos específicos)
  for (const [kw, tipoBase] of TIPO_RULES) {
    if (texto.includes(kw)) {
      return isVentas && VENTAS_VARIANT[tipoBase] ? VENTAS_VARIANT[tipoBase] : tipoBase
    }
  }

  // 2. Código SAT — si el ClaveProdServ pertenece a hardware/cómputo, es PC (Equipo).
  //    Aplica cuando la descripción no tiene keywords reconocibles (ej. genérico "Equipo de trabajo").
  const cp = (claveProdServ || '').trim()
  if (cp && SAT_PC_PREFIXES.some(prefix => cp.startsWith(prefix))) {
    return 'PC (Equipo)'
  }

  // 3. Si ninguna regla matcheó y el concepto es exactamente "TARIFA":
  //    proveedor sin palabras corporativas = persona física (taxista/chofer) → Taxi
  const CORPORATE_WORDS = [
    'S.A', 'S.R.L', 'S.A.S', 'GRUPO ', 'EMPRESA', 'COMPAÑIA', 'COMPANIA',
    'SERVICIOS', 'RESTAURANTE', 'OPERADORA', 'DISTRIBUIDORA', 'COMERCIALIZADORA',
    'CONCESIONARIA', 'ASOCIADOS', 'CORPORATIVO', 'INMOBILIARIA', 'CONSTRUCTORA',
    'TRANSPORTES', 'PROMOTORA', 'ADMINISTRADORA', 'ARRENDADORA', 'HOTELERA',
  ]
  const provUpper = (proveedor || '').toUpperCase()
  const descUpper = (descripcion || '').toUpperCase().trim()
  const isCorporate = CORPORATE_WORDS.some(w => provUpper.includes(w))
  if (descUpper === 'TARIFA' && !isCorporate) {
    return isVentas ? 'Gastos Rep (Representación)' : 'Taxi'
  }

  // 4. Fallback
  return isVentas ? 'Gastos Rep (Representación)' : 'Consumo Viáticos'
}
